download.file(url="https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv", destfile="gdp.csv", method="curl")
download.file(url="https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv", destfile="country.csv", method="curl")
gdp <- read.csv("gdp.csv", header=FALSE, skip=5, nrows=190, na.strings=c("NA","..",""))
country <- read.csv("country.csv")
merged <- merge(gdp, country, by.x="V1", by.y="CountryCode")
x <- gsub(",", "", gdp$V5)
x1 <- gsub(" ", "", x)
y <- as.numeric(x)
mean(y)
z <- grep(gdp$V4, pattern="^United")
length(z)
z1 <- grep(merged$Special.Notes, pattern="^Fiscal year end: June")
length(z1)
